apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-lhtran-net-example
spec:
  acme:
    email: longhtran91@gmail.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-lhtran-net-example
    solvers:
      - dns01:
          route53:
            region: us-east-1
        selector:
          dnsZones:
          - 'lhtran.net'