name: Manage AWS Infrastructure

on:
  workflow_dispatch:
    inputs:
      action:
        type: choice
        description: Environment to create or destroy
        options: 
        - create
        - destroy
jobs:
  terraform:
    runs-on: ubuntu-22.04
    environment: ${{ (github.head_ref || github.ref_name) == 'main' && 'prod' ||  (github.head_ref || github.ref_name) }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform fmt
      run: terraform fmt -check -recursive
      continue-on-error: true

    - name: Terraform Init
      run: |
        export TF_CLOUD_ORGANIZATION=${{ vars.TF_CLOUD_ORGANIZATION }}
        export TF_WORKSPACE=${{ vars.TF_WORKSPACE }}
        terraform init

    - name: Terraform Validate
      run: terraform validate -no-color

    - name: Terraform Apply
      run: |
        export TF_CLOUD_ORGANIZATION=${{ vars.TF_CLOUD_ORGANIZATION }}
        export TF_WORKSPACE=${{ vars.TF_WORKSPACE }}
        terraform apply -auto-approve -var env=${{ vars.ENV_NAME }} ${{ github.event.inputs.action == 'destroy' && '-destroy' }}